/**
 * @file cants/GetBlockManager.hpp
 * @brief Declares the helper that serves and initiates CAN-TS block read transactions.
 */

#pragma once

#include "cannect/Types.hpp"
#include "cannect/cants/Types.hpp"

#include <chrono>
#include <condition_variable>
#include <cstdint>
#include <functional>
#include <mutex>
#include <unordered_map>
#include <vector>
namespace cannect
{

/**
 * @brief Handles CAN-TS GETBLOCK request, acknowledgement, and transfer sequencing.
 */
class GetBlockManager
{
  public:
    /**
     * @brief Sends one protocol frame generated by the manager.
     *
     * The callback should return `true` when the frame was accepted for transmission.
     */
    using FrameSender = std::function<bool(const CanTsHeader &, const uint8_t *, uint8_t)>;

    /**
     * @brief Produces the payload returned for an incoming GETBLOCK request.
     *
     * The response vector should already be arranged as contiguous 8-byte blocks for the
     * requested transfer size.
     */
    using Handler = std::function<bool(uint8_t from, uint8_t channel, std::vector<uint8_t> &response)>;

    /**
     * @brief Creates a manager bound to one local CAN-TS address.
     *
     * @param localAddress Local CAN-TS node address.
     * @param sender Callback used to emit outbound protocol frames.
     */
    GetBlockManager(uint8_t localAddress, FrameSender sender);

    /**
     * @brief Registers the callback used to answer inbound GETBLOCK requests.
     *
     * @param h Request handler that populates the response payload.
     */
    void setHandler(Handler h);

    /**
     * @brief Consumes one decoded GETBLOCK frame.
     *
     * @param h Decoded CAN-TS header.
     * @param frame Payload-bearing CAN frame.
     */
    void onFrame(const CanTsHeader &h, const CanFrame &frame);

    /**
     * @brief Initiates a GETBLOCK transfer from a remote peer.
     *
     * The retrieved payload is cached internally and can be read later with getLastData().
     *
     * @param to Remote node address.
     * @param addressLE Little-endian encoded block address or selector.
     * @param timeoutMs Timeout applied to the acknowledgement and transfer phases.
     * @return true when the complete transfer succeeds, otherwise false.
     *
     * @note The current implementation always requests 64 blocks, which corresponds to
     *       512 bytes at 8 bytes per CAN frame.
     */
    bool getBlock(uint8_t to, const std::vector<uint8_t> &addressLE, uint32_t timeoutMs);

    /**
     * @brief Returns the payload from the last successful GETBLOCK transfer.
     *
     * @param out Output buffer that receives the cached payload.
     * @return true when cached data is available, otherwise false.
     */
    bool getLastData(std::vector<uint8_t> &out) const;

  private:
    struct Session
    {
        uint8_t peer = 0;
        uint8_t channel = 0;
        std::vector<uint8_t> address;
        uint8_t numBlocks = 0;
        std::vector<std::vector<uint8_t>> blocks;
        std::chrono::steady_clock::time_point lastActivity{};
        bool prepared = false;
        bool accepted = false;
    };

    struct PendingState
    {
        bool waitingAck = false;
        bool acked = false;
        bool waitingTransfers = false;
        bool done = false;
        bool ok = false;
        uint8_t peer = 0;
        uint8_t channel = 0;
        uint8_t numBlocks = 0;
        std::vector<std::vector<uint8_t>> blocks;
        std::vector<bool> received;
    };

    uint8_t localAddress;
    FrameSender frameSender;
    Handler handler;

    mutable std::mutex mtx;
    std::condition_variable cv;

    std::unordered_map<uint8_t, Session> sessions;
    PendingState pending;
    std::vector<uint8_t> lastData;
};

} // namespace cannect
