/**
 * @file cants/SetBlockManager.hpp
 * @brief Declares the helper that serves and initiates CAN-TS block write transactions.
 */

#pragma once

#include "cannect/Types.hpp"
#include "cannect/cants/Types.hpp"

#include <chrono>
#include <condition_variable>
#include <cstdint>
#include <functional>
#include <mutex>
#include <unordered_map>
#include <vector>

namespace cannect
{

/**
 * @brief Handles CAN-TS SETBLOCK request, transfer, and completion sequencing.
 */
class SetBlockManager
{
  public:
    /**
     * @brief Sends one protocol frame generated by the manager.
     *
     * The callback should return `true` when the frame was accepted for transmission.
     */
    using FrameSender = std::function<bool(const CanTsHeader &, const uint8_t *, uint8_t)>;

    /**
     * @brief Applies the fully reassembled payload of an inbound SETBLOCK transaction.
     *
     * The request vector contains the concatenated block data received from the peer.
     */
    using Handler = std::function<bool(uint8_t from, uint8_t channel, std::vector<uint8_t> &request)>;

    /**
     * @brief Creates a manager bound to one local CAN-TS address.
     *
     * @param localAddress Local CAN-TS node address.
     * @param sender Callback used to emit outbound protocol frames.
     */
    SetBlockManager(uint8_t localAddress, FrameSender sender);

    /**
     * @brief Registers the callback used to apply inbound SETBLOCK payloads.
     *
     * @param h Handler invoked once all blocks have been reassembled.
     */
    void setHandler(Handler h);

    /**
     * @brief Consumes one decoded SETBLOCK frame.
     *
     * @param h Decoded CAN-TS header.
     * @param frame Payload-bearing CAN frame.
     */
    void onFrame(const CanTsHeader &h, const CanFrame &frame);

    /**
     * @brief Initiates a SETBLOCK transfer to a remote peer.
     *
     * The payload is split into 8-byte blocks, transmitted to the peer, and then checked
     * against the peer's completion report.
     *
     * @param to Remote node address.
     * @param addressLE Little-endian encoded block address or selector.
     * @param data Payload to write.
     * @param timeoutMs Timeout applied to the request and report phases.
     * @return true when the peer reports that all blocks were received and processed.
     */
    bool setBlock(uint8_t to, const std::vector<uint8_t> &addressLE, const std::vector<uint8_t> &data,
                  uint32_t timeoutMs);

  private:
    struct Session
    {
        uint8_t peer = 0;
        uint8_t channel = 0;
        std::vector<uint8_t> address;
        uint8_t numBlocks = 0;
        std::vector<std::vector<uint8_t>> blocks;
        std::chrono::steady_clock::time_point lastActivity{};
        bool prepared = false;
        bool done = false;
        bool accepted = false;
    };

    struct PendingState
    {
        bool active = false;
        bool waitingRequestAck = false;
        bool requestAcked = false;
        bool waitingReport = false;
        bool reportReceived = false;
        bool done = false;
        bool ok = false;
        uint8_t peer = 0;
        uint8_t channel = 0;
        uint8_t numBlocks = 0;
        std::vector<uint8_t> bitmap;
    };

    uint8_t localAddress;
    FrameSender frameSender;
    Handler handler;

    std::mutex mtx;
    std::condition_variable cv;

    std::unordered_map<uint8_t, Session> sessions;
    PendingState pending;
};

} // namespace cannect
